name: _e2e-test

on:
  workflow_call:

env:
  UPLOAD_DIR: soshal-gha/e2e-test/${{ github.sha }}
  ENDPOINT_URL: https://minio-s3.paas.mkizka.dev
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm i
      # https://github.com/FiloSottile/mkcert#linux
      - name: install-mkcert
        run: |
          sudo apt install -y libnss3-tools
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
          chmod +x mkcert-v*-linux-amd64
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
      - run: ./scripts/setup-for-docker.sh
      - run: cp -f .env.docker .env && docker compose up -d --build
      - run: pnpm playwright install --with-deps chromium
      - run: pnpm e2e
      - run: aws --endpoint-url ${{ env.ENDPOINT_URL }} s3 cp reports/e2e-html "s3://${{ env.UPLOAD_DIR }}" --recursive
        if: (success() || failure()) && github.event_name == 'pull_request'
      - uses: gh640/command-result-action@v1
        if: github.event_name == 'pull_request'
        id: e2e-report
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          E2E_TEST_S3_BASEURL: ${{ env.ENDPOINT_URL }}/${{ env.UPLOAD_DIR }}
        with:
          command: ./scripts/e2e-report.ts
      - uses: thollander/actions-comment-pull-request@v2
        if: (success() || failure()) && github.event_name == 'pull_request'
        with:
          message: ${{ steps.e2e-report.outputs.stdout }}
          comment_tag: e2e-report
      - uses: actions/upload-artifact@v3
        if: (success() || failure()) && github.event_name != 'pull_request'
        with:
          name: e2e-${{ github.sha }}
          path: reports/e2e-html
          retention-days: 1
          if-no-files-found: ignore
