name: _e2e-test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i
      - run: pnpm playwright install --with-deps chromium
      - run: ./scripts/setup-for-docker.sh
      - run: cp -f .env.docker .env && docker compose up -d --build
      - run: pnpm e2e
