name: _e2e-test

on:
  workflow_call:

jobs:
  unsocial:
    uses: ./.github/workflows/_e2e-federation.yml
    secrets: inherit
    with:
      target: unsocial
  mastodon:
    uses: ./.github/workflows/_e2e-federation.yml
    secrets: inherit
    with:
      target: mastodon
  misskey:
    uses: ./.github/workflows/_e2e-federation.yml
    secrets: inherit
    with:
      target: misskey
  relay:
    uses: ./.github/workflows/_e2e-federation.yml
    secrets: inherit
    with:
      target: relay
