name: _mutation-test

on:
  workflow_call:

env:
  ENDPOINT_URL: https://minio-s3.paas.mkizka.dev
  BUCKET_NAME: soshal-mutation-test
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm i
      - run: BRANCH_NAME=${{ github.head_ref }} pnpm mutation-test:run-only --fileLogLevel trace
      - name: upload-reports
        run: |
          mv stryker.log reports/
          aws --endpoint-url ${{ env.ENDPOINT_URL }} s3 cp reports "s3://${{ env.BUCKET_NAME }}/${{ github.head_ref }}" --recursive
      - name: show-diff-result
        uses: gh640/command-result-action@v1
        if: ${{ github.event_name == 'pull_request' }}
        id: diff-result
        env:
          MUTATION_TEST_S3_BASEURL: ${{ env.ENDPOINT_URL }}/${{ env.BUCKET_NAME }}/${{ github.head_ref }}
        with:
          command: ./scripts/mutation-report.mts
      - uses: thollander/actions-comment-pull-request@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          message: ${{ steps.diff-result.outputs.stdout }}
          comment_tag: mutation-test-result
