name: _mutation-test

on:
  workflow_call:

env:
  UPLOAD_DIR: soshal-gha/mutation-test/main
  ENDPOINT_URL: https://minio-s3.paas.mkizka.dev
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm i
      - run: pnpm mutation-test:run-only --fileLogLevel trace
      - name: upload-reports
        run: |
          mv stryker.log reports/
          aws --endpoint-url ${{ env.ENDPOINT_URL }} s3 cp reports "s3://${{ env.UPLOAD_DIR }}" --recursive
      - name: show-diff-result
        uses: gh640/command-result-action@v1
        if: ${{ github.event_name == 'pull_request' }}
        id: diff-result
        env:
          MUTATION_TEST_S3_BASEURL: ${{ env.ENDPOINT_URL }}/${{ env.UPLOAD_DIR }}
        with:
          command: ./scripts/mutation-report.mts
      - uses: thollander/actions-comment-pull-request@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          message: ${{ steps.diff-result.outputs.stdout }}
          comment_tag: mutation-test-result
