name: _mutation-test

on:
  workflow_call:

env:
  UPLOAD_DIR: unsocial-gha/mutation-test
  BRANCH_NAME: ${{ github.head_ref || 'main' }}
  ENDPOINT_URL: https://minio-s3.paas.mkizka.dev
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.head_ref == 'renovate/stryker-js-monorepo' || !startsWith(github.head_ref, 'renovate/')
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: pnpm
      - run: pnpm i
      - run: pnpm mutation-test:run-only --fileLogLevel trace
      - name: upload-reports
        run: |
          mv stryker.log reports/mutation/
          aws --endpoint-url ${{ env.ENDPOINT_URL }} s3 cp reports/mutation "s3://${{ env.UPLOAD_DIR }}/${{ env.BRANCH_NAME }}" --recursive
      - uses: gh640/command-result-action@v1
        if: github.event_name == 'pull_request'
        id: mutation-report
        env:
          MUTATION_TEST_S3_BASEURL: ${{ env.ENDPOINT_URL }}/${{ env.UPLOAD_DIR }}
        with:
          command: ./scripts/mutation-report.ts
      - uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: ${{ steps.mutation-report.outputs.stdout }}
          comment_tag: mutation-report
