name: _unit-test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable pnpm
      - run: pnpm --version
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm playwright install --with-deps chromium
      - run: pnpm test:storybook
