name: commit

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    uses: ./.github/workflows/_unit-test.yml
  e2e-test:
    uses: ./.github/workflows/_e2e-test.yml
    secrets: inherit
  mutation-test:
    uses: ./.github/workflows/_mutation-test.yml
    secrets: inherit
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm
      - run: pnpm i
      - uses: changesets/action@v1
        id: changesets
        with:
          publish: pnpm changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.UNSOCIAL_BOT_APP_ID }}
          private-key: ${{ secrets.UNSOCIAL_BOT_PRIVATE_KEY }}
      - name: Merge PR
        if: steps.changesets.outputs.pullRequestNumber > 0
        run: gh pr merge ${{ steps.changesets.outputs.pullRequestNumber }} --squash --delete-branch --admin
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
  deply-docker-image:
    runs-on: ubuntu-latest
    needs: bump-version
    if: needs.bump-version.outputs.published == 'true'
    strategy:
      matrix:
        # https://github.com/changesets/changesets/discussions/1230#discussioncomment-7918696
        package: ${{ fromJson(needs.bump-version.outputs.publishedPackages) }}
    permissions:
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ matrix.package.version }}
            type=raw,value=latest
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  release-sentry:
    runs-on: ubuntu-latest
    needs: bump-version
    if: needs.bump-version.outputs.published == 'true'
    strategy:
      matrix:
        package: ${{ fromJson(needs.bump-version.outputs.publishedPackages) }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_RELEASE: ${{ matrix.package.version }}
  create-renovate-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      BRANCH_NAME: renovate-pr
      PR_TITLE: Renovate Updates
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.UNSOCIAL_BOT_APP_ID }}
          private-key: ${{ secrets.UNSOCIAL_BOT_PRIVATE_KEY }}
        # renovate-prブランチはRulesetによって保護されているので、
        # Bypass listに追加しているbotでpush出来るようにtoken付きでcheckoutする
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Check PR
        id: check-pr
        run: echo "count=$(gh pr list --author 'github-actions[bot]' --search '${{ env.PR_TITLE }}' | wc -l)" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: steps.check-pr.outputs.count == 0
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git switch -c ${{ env.BRANCH_NAME }}
          cp -f .github/workflows/renovate-pr.md .changeset/$(uuidgen).md
          git add .
          git commit -m "${{ env.PR_TITLE }}"
          git push origin ${{ env.BRANCH_NAME }}
          gh pr create -B main -H ${{ env.BRANCH_NAME }} -t "${{ env.PR_TITLE }}" -b ''
