name: commit

on:
  push:
    branches:
      - main

jobs:
  unit-test-prod:
    uses: ./.github/workflows/_unit-test.yml
  e2e-test-prod:
    uses: ./.github/workflows/_e2e-test.yml
  mutation-test-prod:
    uses: ./.github/workflows/_mutation-test.yml
    secrets: inherit
