name: e2e-test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unsocial:
    uses: ./.github/workflows/_e2e-test-workflow.yml
    secrets: inherit
    with:
      target: unsocial
  mastodon:
    uses: ./.github/workflows/_e2e-test-workflow.yml
    secrets: inherit
    with:
      target: mastodon
  misskey:
    uses: ./.github/workflows/_e2e-test-workflow.yml
    secrets: inherit
    with:
      target: misskey
