name: nodejs-test

on:
  pull_request:
    branches:
      - renovate/node-18.x

jobs:
  nodejs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/rtx-action@v1
