name: pr

on:
  pull_request:

jobs:
  unit-test-pr:
    uses: ./.github/workflows/_unit-test.yml
  e2e-test-pr:
    uses: ./.github/workflows/_e2e-test.yml
    secrets: inherit
    permissions:
      pull-requests: write
  mutation-test-pr:
    uses: ./.github/workflows/_mutation-test.yml
    secrets: inherit
    permissions:
      pull-requests: write
