name: pr

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  unit-test:
    uses: ./.github/workflows/_unit-test.yml
  e2e-test:
    uses: ./.github/workflows/_e2e-test.yml
    secrets: inherit
  mutation-test:
    uses: ./.github/workflows/_mutation-test.yml
    secrets: inherit
  nodejs-test:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'renovate/node-')
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/rtx-action@v1
  create-renovate-pr:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: renovate-pr-test
      PR_TITLE: Renovate Updates test
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.UNSOCIAL_BOT_APP_ID }}
          private-key: ${{ secrets.UNSOCIAL_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Check PR
        id: check-pr
        run: echo "count=$(gh pr list --author 'github-actions[bot]' --search '${{ env.PR_TITLE }}' | wc -l)" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: steps.check-pr.outputs.count == 0
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git switch -c ${{ env.BRANCH_NAME }}
          cp -f .github/workflows/renovate-pr.md .changeset/$(uuidgen).md
          git add .
          git commit -m "${{ env.PR_TITLE }}"
          git push origin ${{ env.BRANCH_NAME }}
          gh pr create -B main -H ${{ env.BRANCH_NAME }} -t "${{ env.PR_TITLE }}" -b ''
