name: pr

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  unit-test:
    uses: ./.github/workflows/_unit-test.yml
  e2e-test:
    uses: ./.github/workflows/_e2e-test.yml
    secrets: inherit
  mutation-test:
    uses: ./.github/workflows/_mutation-test.yml
    secrets: inherit
  nodejs-test:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'renovate/node-')
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/rtx-action@v1
  deploy-ghcr:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=tag
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
