name: pr

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  unit-test:
    uses: ./.github/workflows/_unit-test.yml
  e2e-unsocial:
    uses: ./.github/workflows/_e2e-test.yml
    secrets: inherit
    with:
      target: unsocial
  e2e-mastodon:
    uses: ./.github/workflows/_e2e-test.yml
    secrets: inherit
    with:
      target: mastodon
  e2e-misskey:
    uses: ./.github/workflows/_e2e-test.yml
    secrets: inherit
    with:
      target: misskey
  mutation-test:
    uses: ./.github/workflows/_mutation-test.yml
    secrets: inherit
  nodejs-test:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'renovate/node-')
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/rtx-action@v1
