name: renovate

on:
  push:
    branches:
      - renovate-pr

jobs:
  create-renovate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: renovate-pr
      # https://zenn.dev/kshida/articles/auto-generate-release-pr-with-github-actions
      - name: Check PR
        id: check-pr
        run: echo "count=$(gh pr list -S 'Renovate Updates in:title' | wc -l)" >> "$GITHUB_OUTPUT"
      - name: Create PR
        if: steps.check-pr.outputs.count == 0
        run: gh pr create -B main -H renovate-pr -t "Renovate Updates" -b ''
